// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconDash({ size = 24 }: { size?: number }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" width={size} height={size}>
      <path
        d="M19.2 12L4.8 12"
        stroke="currentColor"
        strokeWidth={2}
        strokeLinecap="round"
      />
    </svg>
  );
}
