// this file was generated by scripts/update-icons.ts
// please do not edit it manually

export function IconCheck({ size = 24 }: { size?: number }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" width={size} height={size}>
      <path
        d="M16.8 8.40002L9.64048 15.6L7.2 13.1457"
        stroke="currentColor"
        strokeWidth={2}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}
